version: '3.8'

services:
  shorturl:
    image: shorturlreddis:latest
    build: ./
    hostname: shorturl
    container_name: shorturl
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - shorturl
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: redis-shorturl
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - shorturl
    restart: unless-stopped

volumes:
  redis_data:  

networks:
  shorturl:
      
